config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :questions do
    resources :answers, shallow: true do
      member do
        patch 'mark_best', as: :mark_best
      end
    end
    resource :subscription, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index
  resources :votes, only: %i[create destroy]
  resources :comments, only: :create
  resource :user, only: %i[edit update]
  resource :search, only: [:show]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :best_answer, class_name: 'Answer', optional: true
  has_one :award, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :award, reject_if: proc { |attributes| attributes['name'].blank? }

  validates :title, :body, presence: true

  after_create :subscribe_author

  private

  def subscribe_author
    subscriptions.create(user: author)
  end
end

app/controllers/api/v1/questions_controller.rb
module Api
  module V1
    class QuestionsController < BaseController
      load_and_authorize_resource

      def index
        render json: Question.all, each_serializer: QuestionListSerializer
      end

      def show
        render json: @question
      end

      def create
        @question = current_resource_owner.questions.build(question_params)
        save_and_render(@question, :created)
      end

      def update
        @question.attributes = question_params
        save_and_render(@question)
      end

      def destroy
        @question.destroy
        head :no_content
      end

      private

      def question_params
        params.require(:question).permit(:title, :body, links_attributes: %i[name url])
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show destroy edit update]
  after_action :publish_question, only: :create

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    if current_user
      @answer = Answer.new(question: @question, author: current_user)
      @answer.links.new
    end
    gon.user_id = current_user&.id

    @answers = @question.answers.where.not(id: @question.best_answer_id)
    @best_answer = @question.best_answer
  end

  def new
    @question = current_user.questions.new
    @question.links.new
    @question.build_award
  end

  def create
    @question = current_user.questions.new(params_question)
    if @question.save
      # current_user.associate_award(@question.award)
      redirect_to @question, notice: 'Your question successfully created.'
    else
      flash[:errors] = @question.errors.full_messages
      render :new
    end
  end

  def edit; end

  def update
    @question.update(params_question)
    flash[:errors] = @question.errors.full_messages
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Your question successfully deleted.'
  end

  private

  def params_question
    params.require(:question).permit(:title, :body, files: [], links_attributes: %i[name url],
                                                    award_attributes: %i[name image])
  end

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def publish_question
    return unless @question.valid?

    question_item = ApplicationController.render(
      partial: 'questions/question',
      locals: { question: @question }
    )

    ActionCable.server.broadcast('questions', { question_item: question_item })
  end
end

app/views/questions/_question.html.slim
.question-link
  = link_to "#{question.title}: #{question.body}", question_path(question)

app/views/questions/_question_form.html.slim
- cache question do
  = form_with model: question, local: local do |f|
    div = f.label :title
    div = f.text_field :title

    div = f.label :body
    div = f.text_area :body

    = render 'links/links_form', f: f

    div = f.label :files
    div = f.file_field :files, multiple: true, direct_upload: true

    .award
      h3 Award for the best answer 
      = f.fields_for :award do |award_f|
        = render 'awards/award_fields', f: award_f

    div = f.submit 'Ask' 

app/views/questions/_question_full.html.slim
- cache question do
  div.question id="question-#{question.id}"
    .question-errors
      = render 'shared/errors'

    h4 = "Title: #{question.title}"
    div = "Author: #{question.author.email}"
    div = question.body

    .question-links
      = render question.links

    -if question.files.attached?
      = render partial: 'attachments/attachment', collection: question.files
    
    div id="votable-question-#{question.id}"
      = render 'votes/rating', votable: question
      - if signed_in? && can?(:create_vote, question)
        = render 'votes/vote', vote: question.vote_of(current_user), votable: question

    - if signed_in?
      = render 'subscriptions/subscription', question: question

    - if question.award.present?
      .question-award
        h3 = "For the best answer you will receive #{question.award.name}"
        .question-award-image
          = image_tag question.award.image, size:"250x250"

    - if can?(:destroy, question)
      div = link_to 'Delete question', question_path(question), method: :delete
    - if can?(:update, question)
      div = link_to 'Edit question', '#', class: 'edit-question-link', data: { question_id: question.id }

    div.hidden
      = render 'question_form', question: question, local: false

    = render "comments/comments", commentable: question

app/views/questions/index.html.slim
h1 Questions

p= link_to 'Ask question', new_question_path

ul.questions
  - cache collection_cache_helper_for(:question)
    - @questions.each do |question|
      li = render question

app/views/questions/new.html.slim
h1 New Question

.question-errors
  = render 'shared/errors'

= render 'question_form', question: @question, local: true

app/views/questions/show.html.slim
h2 Question

= render 'question_full', question: @question
br
h2 Answers:

ul.answers
  div.best
    - if @best_answer
      li.answer id="answer-#{@best_answer.id}"
        = "Author: #{@best_answer.author.email}" 
        br
        = @best_answer.body
        br
        - if current_user&.author?(@best_answer)
          div
            = link_to 'Delete answer', answer_path(@best_answer), method: :delete, remote: true
          div
            = link_to 'Edit answer', '#', class: 'edit-answer-link', data: { answer_id: @best_answer.id }
        div.hidden
          = render partial: '/answers/answer_form', locals: { answer: @best_answer, html_data: { id: "edit-answer-#{@best_answer.id}" } }
      p Best!
  - if @answers.present?
    = render @answers
  - else
    p.no_answers No answers

- if current_user
  .new-answer-errors
    = render 'shared/errors'

  div.new_answer_container
    div.new_answer 
      = render '/answers/answer_form', answer: [@question, @answer]

- else
  p You need to be signed in to answer questions

app/views/questions/update.js.erb
<% if flash[:notice].blank? %>
  <% if flash[:errors].present? %>
    $('.question-errors').html('<%= render 'shared/errors' %>');
    $('#question-<%= @question.id %>').replaceWith('<%= j render 'question_full', question: @question.reload %>')
  <% else %>
    $('#question-<%= @question.id %>').replaceWith('<%= j render 'question_full', question: @question%>')
  <% end %>
<% else %>
  $('.notice').html('<%= render 'shared/alerts' %>')
<% end %> 