config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :questions do
    resources :answers, shallow: true do
      member do
        patch 'mark_best', as: :mark_best
      end
    end
    resource :subscription, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index
  resources :votes, only: %i[create destroy]
  resources :comments, only: :create
  resource :user, only: %i[edit update]
  resource :search, only: [:show]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  has_many_attached :files

  validates :body, presence: true

  after_create :send_notification
  before_destroy :clear_best_answer, if: :best_answer?

  def best_answer?
    question.best_answer_id == id
  end

  def mark_as_best_answer
    transaction do
      question.update!(best_answer_id: id)
      question.award&.update!(user: author)
    end
  end

  private

  def clear_best_answer
    question.update(best_answer: nil)
  end

  def send_notification
    NotificationService.new.new_answer(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: %i[new create]
  before_action :load_answer, only: %i[destroy edit update mark_best]
  after_action :publish_answer, only: :create

  authorize_resource

  def new
    @answer = Answer.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(params_answer.merge(author: current_user))

    if @answer.save
      flash.now[:notice] = 'Your answer successfully created.'
    else
      @question.reload
      flash.now[:errors] = @answer.errors.full_messages
    end
    @new_answer = Answer.new
  end

  def update
    @answer.update(params_answer)
    flash[:errors] = @answer.errors.full_messages
  end

  def mark_best
    @prev_best_answer = @answer.question.best_answer
    @answer.mark_as_best_answer
  end

  def destroy
    @answer.destroy
    flash.now[:notice] = 'Your answer successfully deleted.'
  end

  private

  def params_answer
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url])
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def load_question
    @question = Question.with_attached_files.find(params[:question_id])
  end

  def publish_answer
    return unless @answer.valid?

    answer_partial = ApplicationController.render(
      partial: 'answers/answer_pub',
      locals: { answer: @answer }
    )

    data = { answer: answer_partial, user_id: current_user.id }

    QuestionChannel.broadcast_to(@answer.question, data)
  end
end

app/controllers/api/v1/answers_controller.rb
module Api
  module V1
    class AnswersController < BaseController
      load_and_authorize_resource

      def index
        render json: question.answers, each_serializer: AnswerListSerializer
      end

      def show
        render json: @answer
      end

      def create
        @answer = current_resource_owner.answers.where(question: question).build(answer_params)
        save_and_render(@answer, :created)
      end

      def update
        @answer.attributes = answer_params
        save_and_render(@answer)
      end

      def destroy
        @answer.destroy
        head :no_content
      end

      private

      def question
        @question ||= Question.find(params[:question_id])
      end

      def answer_params
        params.require(:answer).permit(:body, links_attributes: %i[name url])
      end
    end
  end
end

app/views/answers/_answer.html.slim
- cache answer do
  li.answer id="answer-#{answer.id}"
    .answer-errors
      = render 'shared/errors'

    div 
      = "Author: #{answer.author.email}"
    div 
      = answer.body

    .answer-links
      = render answer.links

    div
      - if answer.files.attached?
        = render partial: 'attachments/attachment', collection: answer.files
    
    div id="votable-answer-#{answer.id}"
      = render 'votes/rating', votable: answer
      - if signed_in? && can?(:create_vote, answer)
        = render 'votes/vote', vote: answer.vote_of(current_user), votable: answer

    - if can?(:destroy, answer)
      div
        = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
    - if can?(:update, answer)
      div
        = link_to 'Edit answer', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

    div.hidden
      = render partial: '/answers/answer_form', locals: { answer: answer, html_data: { id: "edit-answer-#{answer.id}" } }

    -if can?(:mark_best, answer)
      div
        = link_to 'Best answer', mark_best_answer_path(answer), method: :patch, class: 'best-answer-link', remote: true

    = render "comments/comments", commentable: answer

app/views/answers/_answer_form.html.slim
- cache answer do 
  = form_with model: answer, html: try(:html_data) || {}, local: false do |f|
    div
      = f.label :body
    div
      = f.text_area :body

    = render 'links/links_form', f: f

    div
      = f.label :files
    div
      = f.file_field :files, multiple: true, direct_upload: true

    div 
      = f.submit 'Answer'

app/views/answers/_answer_pub.html.slim
li.answer id="answer-#{answer.id}"
  .answer-errors
    = render 'shared/errors'

  div 
    = "Author: #{answer.author.email}"
  div 
    = answer.body

  .answer-links
    - answer.links.each do |link|
      .link id="link-#{link.id}"
        - if link.gist?
          .gist-link
            = javascript_include_tag link.url+".js"
        - else
          = link_to link.name, url_for(link.url), target: "_blank"

  div
    - if answer.files.attached?
      - answer.files.each do |file|
        div id="attachment-id-#{file.id}"
          div = link_to file.filename.to_s, url_for(file)
  
  div id="votable-answer-#{answer.id}"
    = render 'votes/rating', votable: answer

  div.hidden
    = render partial: '/answers/answer_form', locals: { answer: answer, html_data: { id: "edit-answer-#{answer.id}" } }

  div id="#{answer.class.to_s.underscore}-#{answer.id}-comments"
    h2 Comments:
    .comments-list
      = render answer.comments
    
    = form_with model: Comment.new, class: 'new-comment', local: false do |f|
      = hidden_field_tag :commentable_type, answer.class
      = hidden_field_tag :commentable_id, answer.id
      div = f.label :body, 'New comment'
      div = f.text_area :body
      div = f.submit 'Add comment'

app/views/answers/create.js.erb
$('.new-answer-errors').html('<%= render 'shared/errors' %>');

<%if @answer.persisted? %>
  $('.notice').html('<%= render 'shared/alerts' %>');
  $('.answers').append('<%= j render @answer %>');
  $('.answers .no_answers').remove()
  $('.new_answer form').remove();
  $('.new_answer').append('<%= j render 'answer_form', answer: [@question, @new_answer] %>')
<%end%>

app/views/answers/destroy.js.erb
$('.notice').html('<%= render 'shared/alerts' %>')

$('#answer-<%= @answer.id %>').remove()

if ($('.best li').length == 0) {
  $('.best p').hide()
}

if ($('.answers li').length == 0){
  $('.answers').append('<p class="no_answers">No answers<\/p>')
} 

app/views/answers/mark_best.js.erb
<% if flash[:notice].blank? %>
  $('.best').empty()
  $('#answer-<%= @answer.id %>').remove()
  $('.answers .best').prepend('<%= j render '/answers/answer', answer: @answer %>')
  $('#answer-<%= @answer.id %> .best-answer-link').remove()
  $('.answers .best').append('<p>Best!<\/p>')
  <% if @prev_best_answer %>
    $('.answers .best').after('<%= j render '/answers/answer', answer: @prev_best_answer %>')
  <% end %>
<% else %>
  $('.notice').html('<%= render 'shared/alerts' %>')
<% end %> 

app/views/answers/new.html.slim
h1 New Answer

app/views/answers/show.html.slim
h1 Show Answer

app/views/answers/update.js.erb
<% if flash[:notice].blank? %>
  <% if flash[:errors].present? %>
    $('.answer-errors').html('<%= render 'shared/errors' %>')
    $('#answer-<%= @answer.id %>').replaceWith('<%= j render @answer.reload %>')
  <% else %>
    $('#answer-<%= @answer.id %>').replaceWith('<%= j render @answer%>')
    <%if @answer.best_answer? %>
      $('#answer-<%= @answer.id %> .best-answer-link').remove()
    <%end%>
  <%end%>
<%else%>
  $('.notice').html('<%= render 'shared/alerts' %>')
<%end%>