config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :questions do
    resources :answers, shallow: true do
      member do
        patch 'mark_best', as: :mark_best
      end
    end
    resource :subscription, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index
  resources :votes, only: %i[create destroy]
  resources :comments, only: :create
  resource :user, only: %i[edit update]
  resource :search, only: [:show]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "HelpRequest"
    = Gon::Base.render_data
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': 'reload'
    = javascript_pack_tag "application", 'data-turbolinks-track': 'reload'

  body
    p
      = render '/shared/alerts'

    = link_to 'Questions page', root_path
    = link_to 'Search page', search_path

    - if current_user
      = link_to 'Sign out', destroy_user_session_path, method: :delete
      = link_to 'My awards', awards_path
    - else
      = link_to 'Sign in', new_user_session_path
      = link_to 'Sign up', new_user_registration_path

    = yield